const fakeAuthors = [
  'Ingram Harris',
  'Brigitte Davis',
  'Anton Iverson',
  'Ivana Eriksen',
  'Olive Yew',
  'Aida Bugg',
  'Teri Dactyl',
  'Peg Legge',
  'Allie Grater',
  'Liz Erd',
  'A. Mused',
  'Constance Noring',
  'Minnie Van Ryder',
  'Lynn O’Leeum',
  'P. Ann O’Recital',
  'Ray O’Sun',
  'Lee A. Sun',
  'Ray Sin',
  'Isabelle Ringing',
  'Eileen Sideways',
  'Rita Book',
  'Paige Turner',
  'Rhoda Report',
  'Augusta Wind',
  'Chris Anthemum',
  'Anne Teak',
  'U.R. Nice',
  'Anita Bath',
  'Harriet Upp',
  'I.M. Tired',
  'I. Missy Ewe',
  'Ivana B. Withew',
  'Anita Letterback',
  'Hope Furaletter',
  'B. Homesoon',
  'Bea Mine',
  'Bess Twishes',
  'C. Yasoon',
  'Audie Yose',
  'Dee End',
  'Amanda Hug',
  'Ben Dover',
  'Eileen Dover',
  'Willie Makit',
  'Willie Findit',
  'Skye Blue',
  'Staum Clowd',
  'Addie Minstra',
  'Anne Ortha',
  'Dave Allippa',
  'Dee Zynah',
  'Loco Lyzayta',
  'Manny Jah',
  'Mark Ateer',
  'Reeve Ewer',
  'Tex Ryta',
  'Theresa Green',
  'Barry Kade',
  'Stan Dupp',
  'Neil Down',
  'Con Trariweis',
  'Don Messwidme',
  'Al Annon',
  'Anna Domino',
  'Clyde Stale',
  'Anna Logwatch',
  'Anna Litt',
  'Sly Meebuggah',
  'Saul Goodmate',
  'Faye Clether',
  'Sarah Moanees',
  'Hugo First',
  'Percy Vere',
  'Jack Aranda',
  'Olive Tree',
  'Fran G. Pani',
  'John Quil',
  'Ev R. Lasting',
  'Anne Thurium',
  'Cherry Blossom',
  'Glad I. Oli',
  'Ginger Plant',
  'Del Phineum',
  'Rose Bush',
  'Perry Scope',
  'Frank Stein',
  'Pat Thettick',
  'Percy Kewshun',
  'Rod Knee',
  'Hank Cheef',
  'Pat Toffis',
  'Karen Onnabit',
  'Col Fays',
  'Fay Daway',
  'Joe V. Awl',
  'Colin Sik',
  'Greg Arias',
  'Toi Story'
]

export default fakeAuthors
